name: "Release SDK for Mamoru WIT Agent"
on:
  workflow_dispatch:
    inputs:
      package:
        description: "The package to release"
        required: true
        default: "mamoru-rust-sdk"
        type: choice
        options:
          - mamoru-rust-sdk
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Publish to crates.io
        uses: katyo/publish-crates@v2
        with:
          path: .
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          dry-run: true

